# We(github.com/osoc16/mijn-viaa) changed this file from the original source
# Site settings
title: Mijn VIAA - &num;Soc16
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
